// Order Status Constants - synced with backend enum
export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CLAIMING: 'CLAIMING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_CONFIRM: 'AWAITING_CONFIRM',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
  REFUNDED: 'REFUNDED',
}

// Status display labels
export const STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: 'Pending',
  [ORDER_STATUS.CLAIMING]: 'Claiming',
  [ORDER_STATUS.ASSIGNED]: 'Assigned',
  [ORDER_STATUS.IN_PROGRESS]: 'In Progress',
  [ORDER_STATUS.AWAITING_CONFIRM]: 'Awaiting Confirmation',
  [ORDER_STATUS.COMPLETED]: 'Completed',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
  [ORDER_STATUS.DISPUTED]: 'Disputed',
  [ORDER_STATUS.REFUNDED]: 'Refunded',
}

// Status badge types for styling
export const STATUS_BADGE_TYPES = {
  [ORDER_STATUS.PENDING]: 'secondary',
  [ORDER_STATUS.CLAIMING]: 'info',
  [ORDER_STATUS.ASSIGNED]: 'info',
  [ORDER_STATUS.IN_PROGRESS]: 'warning',
  [ORDER_STATUS.AWAITING_CONFIRM]: 'warning',
  [ORDER_STATUS.COMPLETED]: 'success',
  [ORDER_STATUS.CANCELLED]: 'danger',
  [ORDER_STATUS.DISPUTED]: 'danger',
  [ORDER_STATUS.REFUNDED]: 'secondary',
}

// Valid status transitions (from backend)
export const STATUS_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CLAIMING, ORDER_STATUS.ASSIGNED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CLAIMING]: [ORDER_STATUS.ASSIGNED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.ASSIGNED]: [ORDER_STATUS.IN_PROGRESS, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IN_PROGRESS]: [ORDER_STATUS.AWAITING_CONFIRM, ORDER_STATUS.CANCELLED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.AWAITING_CONFIRM]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.DISPUTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.COMPLETED]: [ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.CANCELLED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.DISPUTED]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.REFUNDED, ORDER_STATUS.CANCELLED, ORDER_STATUS.IN_PROGRESS, ORDER_STATUS.AWAITING_CONFIRM],
  [ORDER_STATUS.REFUNDED]: [],
}

// Get allowed next statuses for a given current status
export const getNextStatuses = (currentStatus) => {
  return STATUS_TRANSITIONS[currentStatus] || []
}

// All statuses for filter buttons
export const ALL_STATUSES = Object.values(ORDER_STATUS)
